### ISSUE TITLE
request to API/site key don't  give stats-kpis anymore

### ISSUE THREAD

**Issue by sakrist** [klaasnicolaas/python-autarco#290]
I tried simple example from Readme and getting exception right away. Looks like API changed.
there is no `stats` and `kpis` in direct request to site.

I think it now required to do request 
`https://my.autarco.com/api/site/[key]/kpis/energy`

<img width="1163" alt="Screenshot 2023-10-28 at 16 45 48" src="https://github.com/klaasnicolaas/python-autarco/assets/110199/a9266561-e8da-4077-b716-3bda63e08685">

**Comment by klaasnicolaas** [comment]
The package is currently no longer up to date because I do not have a test device, I would prefer to change the package to one that works with local and extern API endpoints.

**Comment by klaasnicolaas** [comment]
`https://my.autarco.com/api/site/[key]/kpis/energy`

I don't know what you get in response via this URL, but in the past few days I have completely updated the package and this should now be resolved.
