### ISSUE TITLE
Add Battery Power and State of Charge

### ISSUE THREAD

**Issue by mw25** [klaasnicolaas/python-autarco#486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### How would this feature be useful?

First of all, thank you very much for your work.

In the MyAutarco Platform and now also in the Autarco App you can see the battery power and state of charge.
Could you add these too?

### Describe the solution you'd like

At the MyAutarco Platform I can see they call these requests:

Battery Power:
`https://my.autarco.com/api/site/[key]/batterypack/power`

Battery SOC:
`https://my.autarco.com/api/site/[key]/batterypack/power?f=soc`

**Comment by klaasnicolaas** [comment]
That is certainly possible, but I need to know what the JSON response looks like and possibly also test with the API.

./Klaas

**Comment by mw25** [comment]
Here are the JSON responses in my case today:

Request: 
`https://my.autarco.com/api/site/[key]/batterypack/power?f=soc`

JSON Response (Unit %):
`{"power":{"2024-09-06 00:00:00":76,"2024-09-06 00:15:00":75,"2024-09-06 00:30:00":74,"2024-09-06 00:45:00":72,"2024-09-06 01:00:00":72,"2024-09-06 01:15:00":71,"2024-09-06 01:30:00":70,"2024-09-06 01:45:00":69,"2024-09-06 02:00:00":68,"2024-09-06 02:15:00":67,"2024-09-06 02:30:00":66,"2024-09-06 02:45:00":65,"2024-09-06 03:00:00":64,"2024-09-06 03:15:00":63,"2024-09-06 03:30:00":62,"2024-09-06 03:45:00":61,"2024-09-06 04:00:00":60,"2024-09-06 04:15:00":60,"2024-09-06 04:30:00":59,"2024-09-06 04:45:00":58,"2024-09-06 05:00:00":57,"2024-09-06 05:15:00":56,"2024-09-06 05:30:00":55,"2024-09-06 05:45:00":54,"2024-09-06 06:00:00":51,"2024-09-06 06:15:00":49,"2024-09-06 06:30:00":48,"2024-09-06 06:45:00":48,"2024-09-06 07:00:00":47,"2024-09-06 07:15:00":46,"2024-09-06 07:30:00":46,"2024-09-06 07:45:00":45,"2024-09-06 08:00:00":46,"2024-09-06 08:15:00":47,"2024-09-06 08:30:00":50,"2024-09-06 08:45:00":54,"2024-09-06 09:00:00":58,"2024-09-06 09:15:00":60,"2024-09-06 09:30:00":63,"2024-09-06 09:45:00":66,"2024-09-06 10:00:00":69,"2024-09-06 10:15:00":71}}`

Request: 
`https://my.autarco.com/api/site/[key]/batterypack/power`

JSON Response (Unit W):
`{"power":{"2024-09-06 00:00:00":-201,"2024-09-06 00:15:00":-224,"2024-09-06 00:30:00":-262,"2024-09-06 00:45:00":-183,"2024-09-06 01:00:00":-183,"2024-09-06 01:15:00":-285,"2024-09-06 01:30:00":-195,"2024-09-06 01:45:00":-178,"2024-09-06 02:00:00":-187,"2024-09-06 02:15:00":-190,"2024-09-06 02:30:00":-190,"2024-09-06 02:45:00":-251,"2024-09-06 03:00:00":-266,"2024-09-06 03:15:00":-178,"2024-09-06 03:30:00":-173,"2024-09-06 03:45:00":-176,"2024-09-06 04:00:00":-174,"2024-09-06 04:15:00":-174,"2024-09-06 04:30:00":-174,"2024-09-06 04:45:00":-178,"2024-09-06 05:00:00":-174,"2024-09-06 05:15:00":-177,"2024-09-06 05:30:00":-285,"2024-09-06 05:45:00":-292,"2024-09-06 06:00:00":-771,"2024-09-06 06:15:00":-169,"2024-09-06 06:30:00":-156,"2024-09-06 06:45:00":-151,"2024-09-06 07:00:00":-146,"2024-09-06 07:15:00":-143,"2024-09-06 07:30:00":-125,"2024-09-06 07:45:00":-19,"2024-09-06 08:00:00":180,"2024-09-06 08:15:00":576,"2024-09-06 08:30:00":710,"2024-09-06 08:45:00":992,"2024-09-06 09:00:00":452,"2024-09-06 09:15:00":526,"2024-09-06 09:30:00":728,"2024-09-06 09:45:00":606,"2024-09-06 10:00:00":629,"2024-09-06 10:15:00":1058}}`


In fact, the whole request sent at My.Autarco is:
`https://my.autarco.com/api/site/[key]/batterypack/power?r=day&d=20240906&i=5`
(The response is the same)


I have just noticed that the live values also come from here:
`https://my.autarco.com/api/site/[key]/kpis/power`

Response (key "battery_now" and "battery_soc"):
`{"inverters":{"xxxxx":{"latest":"2024-09-06T08:17:41+00:00","power":961,"health":"OK","error":null}},"pv_now":961,"is_daytime":true,"consumed_now":0,"grid_net_import_now":0,"grid_export_now":0,"consumption_now":184,"self_consumption_now":100,"self_sufficiency_now":100,"battery_now":777,"battery_net_charged_now":777,"battery_soc":71}`

**Comment by klaasnicolaas** [comment]
I have put the responses differently, so it is also more readable for me.

It is a bit of a puzzle how I can throw the first 2 responses in a good way, also with the idea that you could easily use it in Home Assistant. In addition, I also have to look at which values ​​HA wants for batteries.

./Klaas

**Comment by klaasnicolaas** [comment]
What is the response when you access the following URL?

`https://my.autarco.com/api/site/[key]/power`

**Comment by mw25** [comment]
Here is the response.
(My system is not yet properly connected electrically. This could be the reason for the nulls or strange power values.)

```
{
	"dt_config_changed": "2024-03-08T11:01:55+00:00",
	"inverters": {
		"xxxxx": {
			"sn": "xxxxx",
			"dt_latest_msg": "2024-09-09T07:19:18+00:00",
			"out_ac_power": 563,
			"out_ac_energy_total": 4007,
			"error": null,
			"grid_turned_off": false,
			"health": "OK"
		}
	},
	"stats": {
		"graphs": {
			"pv_power": {
				"xxxxx": {
					"2024-09-09 00:00:00": 1,
					"2024-09-09 00:15:00": 1,
					"2024-09-09 00:30:00": 1,
					"2024-09-09 00:45:00": 1,
					"2024-09-09 01:00:00": 1,
					"2024-09-09 01:15:00": 1,
					"2024-09-09 01:30:00": 1,
					"2024-09-09 01:45:00": 1,
					"2024-09-09 02:00:00": 1,
					"2024-09-09 02:15:00": 1,
					"2024-09-09 02:30:00": 1,
					"2024-09-09 02:45:00": 1,
					"2024-09-09 03:00:00": 1,
					"2024-09-09 03:15:00": 1,
					"2024-09-09 03:30:00": null,
					"2024-09-09 03:45:00": null,
					"2024-09-09 04:00:00": null,
					"2024-09-09 04:15:00": null,
					"2024-09-09 04:30:00": null,
					"2024-09-09 04:45:00": null,
					"2024-09-09 05:00:00": null,
					"2024-09-09 05:15:00": null,
					"2024-09-09 05:30:00": null,
					"2024-09-09 05:45:00": null,
					"2024-09-09 06:00:00": 1,
					"2024-09-09 06:15:00": 9,
					"2024-09-09 06:30:00": 26,
					"2024-09-09 06:45:00": 38,
					"2024-09-09 07:00:00": 42,
					"2024-09-09 07:15:00": 45,
					"2024-09-09 07:30:00": 43,
					"2024-09-09 07:45:00": 44,
					"2024-09-09 08:00:00": 46,
					"2024-09-09 08:15:00": 63,
					"2024-09-09 08:30:00": 274,
					"2024-09-09 08:45:00": 444,
					"2024-09-09 09:00:00": 464,
					"2024-09-09 09:15:00": 448
				}
			},
			"no_comms": [],
			"consumed_power": {
				"xxxxx": {
					"2024-09-09 00:00:00": null,
					"2024-09-09 00:15:00": null,
					"2024-09-09 00:30:00": null,
					"2024-09-09 00:45:00": null,
					"2024-09-09 01:00:00": null,
					"2024-09-09 01:15:00": null,
					"2024-09-09 01:30:00": null,
					"2024-09-09 01:45:00": null,
					"2024-09-09 02:00:00": null,
					"2024-09-09 02:15:00": null,
					"2024-09-09 02:30:00": null,
					"2024-09-09 02:45:00": null,
					"2024-09-09 03:00:00": null,
					"2024-09-09 03:15:00": null,
					"2024-09-09 03:30:00": null,
					"2024-09-09 03:45:00": null,
					"2024-09-09 04:00:00": null,
					"2024-09-09 04:15:00": null,
					"2024-09-09 04:30:00": null,
					"2024-09-09 04:45:00": null,
					"2024-09-09 05:00:00": null,
					"2024-09-09 05:15:00": null,
					"2024-09-09 05:30:00": null,
					"2024-09-09 05:45:00": null,
					"2024-09-09 06:00:00": null,
					"2024-09-09 06:15:00": null,
					"2024-09-09 06:30:00": null,
					"2024-09-09 06:45:00": null,
					"2024-09-09 07:00:00": -13,
					"2024-09-09 07:15:00": null,
					"2024-09-09 07:30:00": null,
					"2024-09-09 07:45:00": 14,
					"2024-09-09 08:00:00": -18,
					"2024-09-09 08:15:00": null,
					"2024-09-09 08:30:00": -13,
					"2024-09-09 08:45:00": null,
					"2024-09-09 09:00:00": null,
					"2024-09-09 09:15:00": null
				}
			}
		},
		"kpis": {
			"pv_now": 563,
			"consumed_now": 0
		}
	}
}
```

**Comment by klaasnicolaas** [comment]
These responses do give me more insight into the fact that I may need to approach the data processing for the solar model differently and use the URLs with `kpis`. I didn't know these existed, but I see that we can get a lot more data from them.

./Klaas

**Comment by mw25** [comment]
> I find Autarco's API a bit strange, I would have expected some battery data here as well. 

From what I've seen so far, that's exactly how I feel.


The response for /kpis/energy:

```
{
	"is_daytime": true,
	"pv_today": 1,
	"pv_to_date": 4008,
	"pv_month": 141,
	"co2_today": 0,
	"co2_month": 54,
	"co2_to_date": 1527,
	"grid_net_import_to_date": -787,
	"grid_to_date": -787,
	"grid_import_to_date": 173,
	"grid_in_to_date": 173,
	"grid_import_today": 0,
	"grid_import_month": 1,
	"grid_export_to_date": 960,
	"grid_export_today": 0,
	"grid_export_month": 39,
	"battery_soc": 56,
	"battery_discharged_today": 2,
	"battery_discharged_month": 25,
	"battery_discharged_to_date": 696,
	"battery_out_to_date": 696,
	"battery_charged_today": 1,
	"battery_charged_month": 26,
	"battery_charged_to_date": 748,
	"battery_net_charged_month": 1,
	"battery_net_charged_to_date": 52,
	"battery_to_date": 52,
	"consumption_today": 2,
	"consumption_month": 102,
	"consumption_to_date": 3169,
	"self_sufficiency_month": 100,
	"self_sufficiency_to_date": 100,
	"self_consumption_month": 72,
	"self_consumption_to_date": 76
}
```

**Comment by klaasnicolaas** [comment]
Can you check for me what values ​​the following attributes have?

- has_consumption_meter
- has_battery

With the URL: `https://my.autarco.com/api/site/[key]`

In the meantime I have already created a basic code to retrieve battery data, I will first add this to the Home Assistant integration and then I will see what else can be added.

**Comment by klaasnicolaas** [comment]
I'm also curious about which values ​​of the battery attributes can be negative, for example when you are discharging the battery.

./Klaas

**Comment by mw25** [comment]
The response of `https://my.autarco.com/api/site/[key]/kpis/energy` today in the morning.
Only energy from the battery was used during the night, nothing was generated by PV:

```
{
    "is_daytime": true,
    "pv_today": 0,
    "pv_to_date": 4052,
    "pv_month": 185,
    "co2_today": 0,
    "co2_month": 70,
    "co2_to_date": 1544,
    "grid_net_import_to_date": -797,
    "grid_to_date": -797,
    "grid_import_to_date": 173,
    "grid_in_to_date": 173,
    "grid_import_today": 0,
    "grid_import_month": 1,
    "grid_export_to_date": 970,
    "grid_export_today": 0,
    "grid_export_month": 49,
    "battery_soc": 38,
    "battery_discharged_today": 1,
    "battery_discharged_month": 39,
    "battery_discharged_to_date": 710,
    "battery_out_to_date": 710,
    "battery_charged_today": 0,
    "battery_charged_month": 39,
    "battery_charged_to_date": 761,
    "battery_net_charged_month": 0,
    "battery_net_charged_to_date": 51,
    "battery_to_date": 51,
    "consumption_today": 1,
    "consumption_month": 137,
    "consumption_to_date": 3204,
    "self_sufficiency_month": 100,
    "self_sufficiency_to_date": 100,
    "self_consumption_month": 74,
    "self_consumption_to_date": 76
}
```

The response of `https://my.autarco.com/api/site/[key]/kpis/power:` yesterday in the evening:
When discharging, the battery power is negative.

```
{
	"inverters": {
		"xxxxx": {
			"latest": "2024-09-12T19:31:22+00:00",
			"power": 0,
			"health": "OK",
			"error": null
		}
	},
	"pv_now": 0,
	"is_daytime": false,
	"consumed_now": 0,
	"grid_net_import_now": 0,
	"grid_export_now": 0,
	"consumption_now": 195,
	"self_consumption_now": 0,
	"self_sufficiency_now": 100,
	"battery_now": -195,
	"battery_net_charged_now": -195,
	"battery_soc": 78
}
```

**Comment by mw25** [comment]
> Which attribute indicates how much energy is currently in the battery and not the percentage but the number of Wh or kWh?

Until now I couldn't find any general information about the battery via the API.

**Comment by LauwereinsStijn1989** [comment]
Hej Hej 

I would like to see my battery status in HA.
I came on this 'issue'
Is there already some progress?

Grtz!

**Comment by klaasnicolaas** [comment]
In the upcoming October release of Home Assistant you will be able to retrieve battery data and use it in the energy dashboard.

./Klaas

**Comment by LauwereinsStijn1989** [comment]
That sounds great! 
Will there also be a chance to see the live AC output of the inverter?

Grtz!

**Comment by klaasnicolaas** [comment]
The AC output of the inverters is already included: https://www.home-assistant.io/integrations/autarco/#inverters

./Klaas

**Comment by LauwereinsStijn1989** [comment]
Hej Klaas

For me it looks like this is te same as de solar production.
At night de AC output shows me 0 kwh,when my house is using 800W
At daytime, AC output shows me the same value as the Solar production.

I’m I doing something wrong?
I would like to see the realtime consumption of my house.

Grtz!

 <https://www.varitec.be/>
  Met vriendelijke groeten,
  Stijn Lauwereins

   <tel:+32473627927>   <https://www.instagram.com/VariTec/>   <https://www.facebook.com/VariTecBE>





 <https://www.varitec.be/>

**Comment by klaasnicolaas** [comment]
It seems pretty logical to me that AC output is equal to your solar production since that is only about how much energy your solar panels generate. If you want to know how much your house consumes, you also need to have data about how much you buy and deliver back to/from the grid.

Let's not go off-topic and stick to what this issue is about.

./Klaas

**Comment by LauwereinsStijn1989** [comment]
Totally agree.Thanks for the clarification.Grtz!  Met vriendelijke groeten,  Stijn Lauwereins        Op 30 sep 2024 om 21:50 heeft Klaas Schoute ***@***.***> het volgende geschreven:﻿
It seems pretty logical to me that AC output is equal to your solar production since that is only about how much energy your solar panels generate. If you want to know how much your house consumes, you also need to have data about how much you buy and deliver back to/from the grid.
Let's not go off-topic and stick to what this issue is about.
./Klaas
